Add context to fixer message (#397)
Some code and its fixes failed because LLM does not know the exact
definition of types, e.g.:
```
/src/fuzz_utils.c:55:8: error: no member named 'conn_socket' in 'struct conn_rec'
   55 |     c->conn_socket = sock; // conn_socket is renamed to client_socket
      |     ~  ^
```

This PR adds context of these types to the fixer message when this error
shows up.